language: go
sudo: false
go:
    - 1.8.x
    - 1.9.x
    - tip
install:
    - go get -t -v ./...
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/megacheck
jobs:
    include:
    - stage: unit tests
      script: go test -v -race ./...
    - stage: lint
      script: go vet ./...
      script: golint -set_exit_status
      script: megacheck ./...
