language: go
sudo: false
go:
    - 1.8.x
    - 1.9.x
    - tip
install:
    - go get -t -v ./...
script: go test -v -race ./...
jobs:
    include:
    - stage: lint
      script: go vet ./...
    - script: golint -set_exit_status
      install: go get github.com/golang/lint/golint
    - script: megacheck ./...
      install: go get honnef.co/go/tools/cmd/megacheck
